---
- name: Ping 
  hosts: "{{ seznam_stanic }}" 

  tasks:
  - name: Ping
    win_ping: 
    register: result
    
  - name: ukládání do lokální složky
    local_action: copy content="{{ result }}" dest="/srv/test"
    
