---
- name: Ping 
  hosts: "{{ seznam_stanic }}" 

  tasks:
  - name: Ping
    win_ping: 
    register: result
    
  - name: Log - Fail
    local_action: lineinfile line="{{ ansible_hostname }}" insertafter=EOF dest="/srv/Fail"
    when: result is failed
    
  - name: Log - Success
    local_action: lineinfile line="{{ ansible_hostname }}" insertafter=EOF dest="/srv/Success"
    when: result is success
