---
- name: Ping 
  hosts: "{{ seznam_stanic }}" 

  tasks:
  - name: Ping
    win_ping: 
    register: result
    
  - name: ukládání do lokální složky
    local_action: lineinfile line="{{ ansible_hostname }}" insertafter=EOF dest="/srv/Fail"
    when: result is failed
    
  - name: ukládání do lokální složky
    local_action: lineinfile line="{{ ansible_hostname }}" insertafter=EOF dest="/srv/Success"
    when: result is success
